# Generated by Django 4.1.7 on 2023-06-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceWinguardSketch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('number', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('orders', models.IntegerField()),
                ('date', models.DateField()),
                ('variants', models.IntegerField()),
                ('active', models.IntegerField()),
                ('min_price_for_sort', models.IntegerField()),
            ],
            options={
                'db_table': 'price_winguard_sketch',
            },
        ),
        migrations.CreateModel(
            name='PriceWinguardMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('price_b2c', models.IntegerField()),
                ('price_b2b', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('price_winguard_sketch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.pricewinguardsketch')),
            ],
            options={
                'db_table': 'price_winguard_main',
            },
        ),
        migrations.CreateModel(
            name='PriceWinguardFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_winguard_FilesType_id', models.IntegerField()),
                ('path', models.CharField(max_length=255)),
                ('price_winguard_sketch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.pricewinguardsketch')),
            ],
            options={
                'db_table': 'price_winguard_files',
            },
        ),
    ]
